### ISSUE TITLE
todo-core模块分包

### ISSUE THREAD

**Issue by comeCU** [dreamhead/geektime-todo#7]
请教下老师todo-core模块有必要分包吗，还是说代码比较少放一起，如果分包应该是怎么样子的呢
- `domain` or `model`  ?
  TodoItem、TodoParameter、TodoIndexParameter
- `service`
  TodoItemService
- `repository`
  TodoItemRepository
- `exception`
  TodoException

**Comment by dreamhead** [comment]
分包有几种不同的做法，一种是你的做法，按照不同的层进行分包，另外一种做法是，根据业务功能进行分包，把相关的代码都放到一起。我现在的做法你可以理解是第二种。

**Comment by comeCU** [comment]
现在理解了，Thoughtworks钟敬老师 “打横与打竖”的分包方式。“打横”按层次分；“打竖”按耦合性。
